aws-actions/amazon-ecs-deploy-task-definition

README.md
action.yml
index.js
index.test.js
package-lock.json
package.json

Duplicate much of the logic from the `aws ecs deploy` command into this action, so that Actions can be used to deploy to CodeDeploy-using ECS services.

Support for CodeDeploy deployments

---

index.js
index.test.js

fix: Ignore task definition fields that are Describe outputs, but not Register inputs

---

index.js
index.test.js

Fixes #48 
Somehow the console generated this invalid task definition, which includes both an empty tags array and an empty string for credentialsParameter, neither of which are accepted by RegisterTaskDefinition.  I added unit tests for both these cases
https://github.com/ahmednkhan24/node-to-aws/blob/master/task-definition.json

feat: clean empty arrays and objects from the task def file

---

index.js
index.test.js

feat: Add more debugging, including link to the ECS or CodeDeploy console

---

index.js
index.test.js

Fixes #53 
The following task definition input for the action:
```
"logConfiguration": {
"logDriver": "awsfirelens",
"options": {
"KeyName": ""
},
"secretOptions": [
{
"name": "",
"valueFrom": ""
}
]
},
```
currently generates the following input to RegisterTaskDefinition:
```
"logConfiguration": {
"logDriver": "awsfirelens",
"secretOptions": [
null
]
},
```
Because of the null value, the only error message is `Cannot read property 'name' of null`.  This PR removes all the null values so that a proper error message is given to the user.

fix: clean null values out of arrays

---

index.js
index.test.js

*This PR fix the Issue [#133](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/133)*
This issue was occurring due to incorrect data type of the forceNewDeployment parameter.
In order to fix this issue need to type caste the value of the forceNewDeployment parameter from string to boolean.

fix: forceNewDeployment to be a boolean

---

index.js

Return false if there is no forceNewDeployment value passed in as input.

fix: forceNewDeployment input to take a boolean

---

index.js
index.test.js

Addresses https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/164

fix: ignore additional fields from task definition input

---

index.js
index.test.js

fix: forceNewDeployment to be a boolean.

---

index.js
index.test.js
package-lock.json

Fixes: #163
App Mesh requires the properties array contain a name and a value for each key. The `cleanNullKeys` removes the values that are empty strings. This commit loops through the properties array if the proxyConfiguration.type is APPMESH and restores any deleted values.

fix: allow empty values in proxyConfiguration.properties

---

index.js
index.test.js

This PR fix the issue #216  
The **cleanNullKeys** function removes all the null/undefined/empty parameters from the task def json which removes empty environment variables as well. After removing empty environment variables task def json looks something like following where value parameter is completely being omitted from the task def json - 
```
"environment": [
{
"name": "DEMO_VAR"
},
{
"name": "APP_PLACEHOLDER_SERVICE",
"value": "ecs-demo-site"
},
{
"name": "APP_PLACEHOLDER_ENV",
"value": "qa"
},
{
"name": "APP_PLACEHOLDER_PORT",
"value": "80"
}
]
```
When GH action deploys this task def then ECS removes the complete object with no value field from the environment array of the task def which looks like following and causes deployment to fail in case that particular environment …

fix: Container Definition Environment variables are being removed when empty

---

.mergify.yml

Mergify deprecated strict mode in order to specify different conditions to get the PR in the queue and to get it merged. In order to solve this breaking change we will be changing mergify logic to have new queue_rules one as default for CI success and another for automated dependabot merges. Please follow the [link](https://blog.mergify.com/strict-mode-deprecation/) for more information.

fix: Strict Mode Deprecation

---

index.js
index.test.js

The China region's console is located at https://console.amazonaws.cn/.
This PR checks the region configured and prints the correct console link
since the global console doesn't auto redirect.

fix: Use correct host for China region console

---

index.js
index.test.js

Fixes #384.
Thanks @bradens for the fix! (original PR: #385)

fix: support new 'ECS' deployment type rather than relying on a null value

---

action.yml

The new version of `ncc` (#390) generates js with optional chaining. Need to update the node runtime of the GH action to support that.

chore: update action runtime to node16

---

index.test.js
package-lock.json
package.json

*Issue #, if available:* #401 and replaces #394
Bumps @actions/core from 1.6.0 to 1.10.0 which resolves the use of deprecated set-output command. Also fixed test due to change in 1.7.0

chore: Bump @actions/core from 1.6.0 to 1.10.0, resolves #401

---

action.yml
index.js
index.test.js

I would like to ask for help in the PR, as I can't fix 1 test which is failing.
*Issue #499*
*Add support for DesiredCount*
it would be great to have DesiredCount support during deployment.
https://docs.aws.amazon.com/cli/latest/reference/ecs/update-service.html
--desired-count

feat: Add desired tasks

---

.github/workflows/check.yml
.github/workflows/codeql-analysis.yml

Updated the following actions to to their latest versions that use Nodejs20 and other updated dependencies. Following versions are using Nodejs 16 or older nodejs versions, this upgrade will switch them all to Node.js 20 (latest release of the respective actions).
* actions/github-scripts@v6 to v7
* github/codeql-action/init@v1 to v3
* github/codeql-action/autobuild@v1 to v3
* github/codeql-action/analyze@v1 to v3
For more information see:
* https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
* https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …

chore(ci): Upgrade github workflows to non-deprecated runtimes

---

action.yml

The description for the "service" param states:
> "The name of the ECS service to deploy to. The action will only register the task definition if no service is given."
But in this case "only" is not meant as a condition, but as a limitation...
I stumbled upon this ambiguity in the documentation and it cost me an hour of my life, so I thought I might as well change it :-) 

docs: make description for "service" parameter less ambiguous.

---

action.yml
dist/index.js
index.js
index.test.js

Allows to overwrite the desired deployment configuration for CodeDeploy

feat: add CodeDeploy deployment config name parameter

---

dist/index.js
index.js
index.test.js
package-lock.json

The url to check the events is using the v1, the v2 has been released since around Jan 2023 and isn't backward compatible. Just a Quality of Life thing

fix: Link to events v2 url

---

README.md
action.yml
dist/index.js
index.js
index.test.js

*Issue #, if available:* #54 
*Description of changes:* This adds the ability to run tasks outside of a service, either standalone or as an init task. 
This borrows a lot from #273 but offers a slightly cleaner interface and isn't dependent on a service.
EDIT: In case you're seeing this and want to use it, you can pull it directly from the PR in your GitHub Actions workflow (see below). We've been using it in production for months now and I'm happy to keep supporting it.
```yaml
- name: Deploy Amazon ECS task definition
id: deploy-task-def
uses: inhumantsar/amazon-ecs-deploy-task-definition@feat/run-task
with:
task-definition: ${{ …
```

feat: add ad-hoc task runs

---

README.md

Update readme to reference v2 version tag of deploy-task-definition action

docs: Update readme to reference v2 version tag

---

README.md

*Issue #, if available:*https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/608#issuecomment-2275957302
*Description of changes:* 
Added a section for permissions needed to run a one-off/stand-alone task 

chore: modified README.md file with permissions for one off task

---

README.md
action.yml
dist/index.js
index.js
index.test.js

https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/616
This PR sets networkConfiguration to null when neither subnetIds nor securityGroupIds are set. This fixes run task whenever launch type is EC2. I tested this branch with the github workflow I'm building and it works to run migrations as a task.
There was one failing test which I changed. I wonder whether this should only apply when the launchType is EC2 though? Let me know what you think

fix: set networkConfiguration to null when using bridge network mode

---

action.yml

Added a missing parenthesis in the action output description

docs: added a missing parenthesis in the action output description

---

action.yml
dist/index.js
index.js
index.test.js

When you use cluster auto scaling, you must specify `capacityProviderStrategy` and not `launchType` (as mentioned in the [RunTask](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#ECS-RunTask-request-capacityProviderStrategy) documentation). Unfortunately this is currently not possible to configure when running a one-off task with this action.
None
This adds a new input `run-task-capacity-provider-strategy` which takes a JSON array of capacity provider strategy items. When this is specified, `run-task-launch-type` will not be applied.

feat: add run-task-capacity-provider-strategy input

---

.github/workflows/notifications.yml
dist/index.js

- Avoid injection attacks by adding basic user input sanitation

chore: Sanitize titles for Slack notification

---

.github/workflows/notifications.yml

- Before sending notification to Slack, replace any quotes that exist in Github entity title

chore: Replace quotes when sanitizing title

---

README.md
action.yml
dist/index.js
index.js
index.test.js

*Issue #, if available: n/A
This PR enhances the `amazon-ecs-deploy-task-definition` GitHub Action to support Amazon ECS Managed EBS Volumes for both RunTask and UpdateService operations. The changes include:
1. Introduced new input parameters:
- `run-task-managed-ebs-volume-name`
- `run-task-managed-ebs-volume`
- `service-managed-ebs-volume-name`
- `service-managed-ebs-volume`
2. Added support for VolumeConfiguration property during runTask api call if the `run-task-managed-ebs-volume-name`
and `run-task-managed-ebs-volume` parameters have been set.
3. Added support for VolumeConfiguration property during updateService api call if the `service-managed-ebs-volume-name` and `service-managed-ebs-volume` parameters have been set. 
To use `VolumeConfigurations` property in `runTask` and …

feat: Add support for 'VolumeConfigurations' property on both UpdateService and RunTask API call

---

.github/workflows/test-workflow.yml
task-definition-run-task-volume-configuration.json
task-definition-volume-configuration.json
test-workflow.yml

Adding integration tests for the VolumeConfiguration property added as part of: https://github.com/aws-actions/amazon-ecs-deploy-task-definition/pull/721

chore: add integration test for VolumeConfiguration property

---

action.yml

- none
- In https://github.com/aws-actions/amazon-ecs-deploy-task-definition/pull/304, the addition of the `run-task-arn` output implemented [in index.js](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/blob/8ef49e87170f62b9e341907dc88cffc1615e3b0d/index.js#L85) was accidentally omitted from action.yml.
- This fix allows users of this action to reference the ARN of the executed task, thereby enhancing usability.

fix: propagate `run-task-arn` to outputs
